services:
  app:
    build:
      context: .
    volumes:
      - .:/opt/lampp/htdocs/pr_comercio_electronico/
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: php artisan serve --host=0.0.0.0 --port=8000

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: pr_comercio_electronic
    ports:
      - "3306:3306"
